spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: LAZY
  jpa:
    hibernate:
      ddl-auto: validate
      id:
        new_generator_mappings: false
  flyway:
    baseline-on-migrate: true
  cloud:
    stream:
      bindings:
        balls:
          group: 'referee'
          consumer:
            prefetch: 20
  datasource:
    hikari:
      jdbc-url: 'jdbc:h2:mem:playerdb'