spring:
  data:
    jpa:
      repositories:
        bootstrap-mode: LAZY
  jpa:
    hibernate:
      ddl-auto: validate
      id:
        new_generator_mappings: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    baseline-on-migrate: true
  cloud:
    stream:
      bindings:
        balls:
          group: 'referee'